### PR TITLE
Giving option for deterministic Youtube search behavior

### PR DESCRIPTION
**Pull request by thomasrussellmurphy**
@dualmoon suggested in their own fork of hubot-youtube to only search for the most relevant result. This would change the behavior to be fully deterministic and only return the top YouTube search result rather than a random result from the top 15.

### CODE REVIEW

**Comment by Emile-Filteau** [comment]
Since April 20 the Youtube API V2 is deprecated. When using the deprecated API, the most relevant result is always this video : 
http://www.youtube.com/watch?v=UKY3scPIMd8&feature=youtube_gdata

I managed to make a little work around by putting max-results to 2 and replacing 
```
video  = msg.random videos
```

by
```
video  = videos[1]
```

**Comment by stephenyeargin** [comment]
I've got another fix in #3 that adds an API key (which appears to now be required for the v3 API) to take care of the second bit.

As for the "most relevant" thing, I believe this is supposed to behave like image search, in so far as it purposefully returns a random relevant(-ish) result. I could be wrong about the intent.

**Comment by Emile-Filteau** [comment]
I think a good way would be to add an optional switch (like -random) that sets maxResults to 15 otherwise maxResults is 1. So both use case are handled with minimal code change.
@stephenyeargin what do you think ?

**Comment by stephenyeargin** [comment]
For the simplicity of this particular module, and how I have seen it in the wild, I'd say make it a configuration option, e.g. `YOUTUBE_MAX_RESULTS`, rather than a flag in the command itself.

I usually see the package used in this scenario:

>Really? You've never heard of cat breading?!?
>`!yt cat breading`
>... No, that's not it. ...
>`!yt cat breading` ....
>_There_ it is. LOL

**Comment by technicalpickles** [comment]
I tend to see hubot used in the same way as @stephenyeargin described. That is also how some other scripts like `hubot img me` and `hubot pug me` work.

Having a YOUTUBE_MAX_RESULTS makes sense, or maybe call it more descriptively like YOUTUBE_DETERMINISTIC_RESULTS to indicate it gives you the same result from youtube everytime.

**Comment by thomasrussellmurphy** [comment]
That sounds pretty good. If someone with more experience with Coffeescript/Hubot wants to add that configuration option, that would be great.

Changing title to reflect new goal.

**Comment by technicalpickles** [comment]
```coffeescript
    maxResults = if process.env.HUBOT_YOUTUBE_MAX_RESULTS?
      parseInt(process.env.HUBOT_YOUTUBE_MAX_RESULTS)
    else
      15
    robot.http("http://gdata.youtube.com/feeds/api/videos")
      .query({
        orderBy: "relevance"
        'max-results': maxResults
        alt: 'json'
        q: query
      })
```

**Comment by technicalpickles** [comment]
```coffeescript
    maxResults = if process.env.HUBOT_YOUTUBE_DETERMINISTIC_RESULTS == 'true'
      1
    else
      15
    else
      15
    robot.http("http://gdata.youtube.com/feeds/api/videos")
      .query({
        orderBy: "relevance"
        'max-results': maxResults
        alt: 'json'
        q: query
      })
```

Reading that now, it could be confusing that you are getting a consistent reply from youtube, since feasibly the relevance could change as videos are posted or whatever.

In addition to this, there'd need to be some documentation in the README.

**Comment by thomasrussellmurphy** [comment]
There are some commits that should cover the new code and the documentation. I have not run the tests too see if this code functions, however.

**Comment by technicalpickles** [comment]
@thomasrussellmurphy please test, and if it looks good we can merge it. Note: the unit tests aren't comprehensive here, so you'll want to manually test this in a bot.

**Comment by thomasrussellmurphy** [comment]
Currently blocked by #3

**Comment by stephenyeargin** [comment]
Yep, one task in #4 to rename a ENV and then we can :shipit:

**Comment by thomasrussellmurphy** [comment]
Merged changes from upstream implementing the API v3 changes and added documentation for the `HUBOT_YOUTUBE_DETERMINISTIC_RESULTS` environment variable.

**Comment by stephenyeargin** [comment]
I'm :+1: with this one.

**Pull request merged**
